### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by camohub** [paveljanda/happy#16]
As you know Bower is no longer supported. Can you make NPM package to use in projects. You have something for NPM **but it is not compiled**. Happy.js throws me an error **Uncaught SyntaxError: Unexpected token 'export'** 
Thanks a lot.

**Comment by paveljanda** [comment]
Will do

**Comment by paveljanda** [comment]
https://github.com/paveljanda/happy

https://github.com/paveljanda/happy/releases/tag/v2.1.0
