### ISSUE TITLE
Add into bower/npm package manager

### ISSUE THREAD

**Issue by juniwalk** [paveljanda/happy#3]
Sorry for being so pesky,
first composer now this, but I switched to [this composer plugin](https://github.com/francoispluchino/composer-asset-plugin) which installs my assets into www/assets and this gives me much more control over by assets in webloader, it would be great having happy there too :)

**Comment by paveljanda** [comment]
`bower install happy`

If you are using datagrid, look at https://github.com/ublaboo/datagrid/issues/102 for more informations. I will add some more docu to project sites.

**Comment by juniwalk** [comment]
Thank you very much! :)
