### ISSUE TITLE
Change directory structure to follow standard

### ISSUE THREAD

**Issue by juniwalk** [paveljanda/happy#4]
Since this package is on bower now you should really consider changing directory structure like I mentioned in #1.

This is standard for frontend components and would probably be best to follow it.

> `/dist <- compiled assets`
> `/src <- source assets`

If you want I can send PR. :)

**Comment by paveljanda** [comment]
It would be perfect, if you sent a PR. You can do that also in paveljanda/happy repo - there are css/sass files too. :)

**Comment by juniwalk** [comment]
Great, I will look into it, you will have to check my changes as I have zero experience with frontend :)

**Comment by paveljanda** [comment]
Roger that.

**Comment by paveljanda** [comment]
Sorry, i just want to release v2 (documentation ready etc) od datagrid, so I did it.
